"""Map SPDX licence identifiers onto the vocabulary bio.tools accepts.

``license_normalizer`` emits current SPDX identifiers, which is right as SPDX
and wrong for bio.tools: biotoolsSchema froze its licence enumeration on the
pre-2019 SPDX list, before the ``-only`` suffix existed. So ``GPL-3.0-only`` is
a valid SPDX identifier and an invalid bio.tools value, while
``GPL-3.0-or-later`` is valid in both.

An identifier outside the enumeration makes the bio.tools API reject the whole
record with HTTP 400. That is what happened to 1,008 tools in the import run of
2026-08-30:

    ERROR:root:Error validating update for a4: 400
    {"license": ["Invalid value: GPL-3.0-only."], ...}

The allow-list below is the licence enumeration copied from biotoolsSchema
(``stable/biotools.xsd``, 435 distinct values). Keep it in step with the schema.
"""

import re

# Licence enumeration from biotoolsSchema stable/biotools.xsd.
BIOTOOLS_LICENSES = frozenset(
    {
        "0BSD",
        "AAL",
        "ADSL",
        "AFL-1.1",
        "AFL-1.2",
        "AFL-2.0",
        "AFL-2.1",
        "AFL-3.0",
        "AGPL-1.0",
        "AGPL-3.0",
        "AMDPLPA",
        "AML",
        "AMPAS",
        "ANTLR-PD",
        "APAFML",
        "APL-1.0",
        "APSL-1.0",
        "APSL-1.1",
        "APSL-1.2",
        "APSL-2.0",
        "Abstyles",
        "Adobe-2006",
        "Adobe-Glyph",
        "Afmparse",
        "Aladdin",
        "Apache-1.0",
        "Apache-1.1",
        "Apache-2.0",
        "Artistic-1.0",
        "Artistic-1.0-Perl",
        "Artistic-1.0-cl8",
        "Artistic-2.0",
        "BSD-2-Clause",
        "BSD-2-Clause-FreeBSD",
        "BSD-2-Clause-NetBSD",
        "BSD-3-Clause",
        "BSD-3-Clause-Attribution",
        "BSD-3-Clause-Clear",
        "BSD-3-Clause-LBNL",
        "BSD-3-Clause-No-Nuclear-License",
        "BSD-3-Clause-No-Nuclear-License-2014",
        "BSD-3-Clause-No-Nuclear-Warranty",
        "BSD-4-Clause",
        "BSD-4-Clause-UC",
        "BSD-Protection",
        "BSD-Source-Code",
        "BSL-1.0",
        "Bahyph",
        "Barr",
        "Beerware",
        "BitTorrent-1.0",
        "BitTorrent-1.1",
        "Borceux",
        "CATOSL-1.1",
        "CC-BY-1.0",
        "CC-BY-2.0",
        "CC-BY-2.5",
        "CC-BY-3.0",
        "CC-BY-4.0",
        "CC-BY-NC-1.0",
        "CC-BY-NC-2.0",
        "CC-BY-NC-2.5",
        "CC-BY-NC-3.0",
        "CC-BY-NC-4.0",
        "CC-BY-NC-ND-1.0",
        "CC-BY-NC-ND-2.0",
        "CC-BY-NC-ND-2.5",
        "CC-BY-NC-ND-3.0",
        "CC-BY-NC-ND-4.0",
        "CC-BY-NC-SA-1.0",
        "CC-BY-NC-SA-2.0",
        "CC-BY-NC-SA-2.5",
        "CC-BY-NC-SA-3.0",
        "CC-BY-NC-SA-4.0",
        "CC-BY-ND-1.0",
        "CC-BY-ND-2.0",
        "CC-BY-ND-2.5",
        "CC-BY-ND-3.0",
        "CC-BY-ND-4.0",
        "CC-BY-SA-1.0",
        "CC-BY-SA-2.0",
        "CC-BY-SA-2.5",
        "CC-BY-SA-3.0",
        "CC-BY-SA-4.0",
        "CC0-1.0",
        "CDDL-1.0",
        "CDDL-1.1",
        "CECILL-1.0",
        "CECILL-1.1",
        "CECILL-2.0",
        "CECILL-2.1",
        "CECILL-B",
        "CECILL-C",
        "CNRI-Jython",
        "CNRI-Python",
        "CNRI-Python-GPL-Compatible",
        "CPAL-1.0",
        "CPL-1.0",
        "CPOL-1.02",
        "CUA-OPL-1.0",
        "Caldera",
        "ClArtistic",
        "Condor-1.1",
        "Crossword",
        "CrystalStacker",
        "Cube",
        "D-FSL-1.0",
        "DOC",
        "DSDP",
        "Dotseqn",
        "ECL-1.0",
        "ECL-2.0",
        "EFL-1.0",
        "EFL-2.0",
        "EPL-1.0",
        "EPL-2.0",
        "EUDatagrid",
        "EUPL-1.0",
        "EUPL-1.1",
        "Entessa",
        "ErlPL-1.1",
        "Eurosym",
        "FSFAP",
        "FSFUL",
        "FSFULLR",
        "FTL",
        "Fair",
        "Frameworx-1.0",
        "FreeImage",
        "GFDL-1.1",
        "GFDL-1.2",
        "GFDL-1.3",
        "GL2PS",
        "GPL-1.0",
        "GPL-2.0",
        "GPL-3.0",
        "Giftware",
        "Glide",
        "Glulxe",
        "HPND",
        "HaskellReport",
        "IBM-pibs",
        "ICU",
        "IJG",
        "IPA",
        "IPL-1.0",
        "ISC",
        "ImageMagick",
        "Imlib2",
        "Info-ZIP",
        "Intel",
        "Intel-ACPI",
        "Interbase-1.0",
        "JSON",
        "JasPer-2.0",
        "LAL-1.2",
        "LAL-1.3",
        "LGPL-2.0",
        "LGPL-2.1",
        "LGPL-3.0",
        "LGPLLR",
        "LPL-1.0",
        "LPL-1.02",
        "LPPL-1.0",
        "LPPL-1.1",
        "LPPL-1.2",
        "LPPL-1.3a",
        "LPPL-1.3c",
        "Latex2e",
        "Leptonica",
        "LiLiQ-P-1.1",
        "LiLiQ-R-1.1",
        "LiLiQ-Rplus-1.1",
        "Libpng",
        "MIT",
        "MIT-CMU",
        "MIT-advertising",
        "MIT-enna",
        "MIT-feh",
        "MITNFA",
        "MPL-1.0",
        "MPL-1.1",
        "MPL-2.0",
        "MPL-2.0-no-copyleft-exception",
        "MS-PL",
        "MS-RL",
        "MTLL",
        "MakeIndex",
        "MirOS",
        "Motosoto",
        "Multics",
        "Mup",
        "NASA-1.3",
        "NBPL-1.0",
        "NCSA",
        "NGPL",
        "NLOD-1.0",
        "NLPL",
        "NOSL",
        "NPL-1.0",
        "NPL-1.1",
        "NPOSL-3.0",
        "NRL",
        "NTP",
        "Naumen",
        "NetCDF",
        "Newsletr",
        "Nokia",
        "Noweb",
        "Nunit",
        "OCCT-PL",
        "OCLC-2.0",
        "ODbL-1.0",
        "OFL-1.0",
        "OFL-1.1",
        "OGTSL",
        "OLDAP-1.1",
        "OLDAP-1.2",
        "OLDAP-1.3",
        "OLDAP-1.4",
        "OLDAP-2.0",
        "OLDAP-2.0.1",
        "OLDAP-2.1",
        "OLDAP-2.2",
        "OLDAP-2.2.1",
        "OLDAP-2.2.2",
        "OLDAP-2.3",
        "OLDAP-2.4",
        "OLDAP-2.5",
        "OLDAP-2.6",
        "OLDAP-2.7",
        "OLDAP-2.8",
        "OML",
        "OPL-1.0",
        "OSET-PL-2.1",
        "OSL-1.0",
        "OSL-1.1",
        "OSL-2.0",
        "OSL-2.1",
        "OSL-3.0",
        "OpenSSL",
        "PDDL-1.0",
        "PHP-3.0",
        "PHP-3.01",
        "Plexus",
        "PostgreSQL",
        "Python-2.0",
        "QPL-1.0",
        "Qhull",
        "RHeCos-1.1",
        "RPL-1.1",
        "RPL-1.5",
        "RPSL-1.0",
        "RSA-MD",
        "RSCPL",
        "Rdisc",
        "Ruby",
        "SAX-PD",
        "SCEA",
        "SGI-B-1.0",
        "SGI-B-1.1",
        "SGI-B-2.0",
        "SISSL",
        "SISSL-1.2",
        "SMLNJ",
        "SMPPL",
        "SNIA",
        "SPL-1.0",
        "SWL",
        "Saxpath",
        "Sendmail",
        "SimPL-2.0",
        "Sleepycat",
        "Spencer-86",
        "Spencer-94",
        "Spencer-99",
        "SugarCRM-1.1.3",
        "TCL",
        "TMate",
        "TORQUE-1.1",
        "TOSL",
        "UPL-1.0",
        "Unicode-TOU",
        "Unlicense",
        "VOSTROM",
        "VSL-1.0",
        "Vim",
        "W3C",
        "W3C-19980720",
        "WTFPL",
        "Watcom-1.0",
        "Wsuipa",
        "X11",
        "XFree86-1.1",
        "XSkat",
        "Xerox",
        "Xnet",
        "YPL-1.0",
        "YPL-1.1",
        "ZPL-1.1",
        "ZPL-2.0",
        "ZPL-2.1",
        "Zed",
        "Zend-2.0",
        "Zimbra-1.3",
        "Zimbra-1.4",
        "Zlib",
        "bzip2-1.0.5",
        "bzip2-1.0.6",
        "curl",
        "diffmark",
        "dvipdfm",
        "eGenix",
        "gSOAP-1.3b",
        "gnuplot",
        "iMatix",
        "libtiff",
        "mpich2",
        "psfrag",
        "psutils",
        "xinetd",
        "xpp",
        "zlib-acknowledgement",
        "AGPL-1.0-or-later",
        "AGPL-3.0-or-later",
        "ANTLR-PD-fallback",
        "blessing",
        "BlueOak-1.0.0",
        "BSD-1-Clause",
        "BSD-2-Clause-Patent",
        "BSD-2-Clause-Views",
        "BSD-3-Clause-Modification",
        "BSD-3-Clause-No-Military-License",
        "BSD-3-Clause-Open-MPI",
        "BSD-4-Clause-Shortened",
        "BUSL-1.1",
        "CAL-1.0",
        "CAL-1.0-Combined-Work-Exception",
        "CC-BY-3.0-AT",
        "CC-BY-3.0-US",
        "CC-BY-NC-ND-3.0-IGO",
        "CC-BY-SA-2.0-UK",
        "CC-BY-SA-2.1-JP",
        "CC-BY-SA-3.0-AT",
        "CC-PDDC",
        "CDL-1.0",
        "CDLA-Permissive-1.0",
        "CDLA-Sharing-1.0",
        "CERN-OHL-1.1",
        "CERN-OHL-1.2",
        "CERN-OHL-P-2.0",
        "CERN-OHL-S-2.0",
        "CERN-OHL-W-2.0",
        "copyleft-next-0.3.0",
        "copyleft-next-0.3.1",
        "C-UDA-1.0",
        "DRL-1.0",
        "EPICS",
        "etalab-2.0",
        "EUPL-1.2",
        "FreeBSD-DOC",
        "GD",
        "GFDL-1.1-invariants-only",
        "GFDL-1.1-invariants-or-later",
        "GFDL-1.1-no-invariants-only",
        "GFDL-1.1-no-invariants-or-later",
        "GFDL-1.1-or-later",
        "GFDL-1.2-invariants-only",
        "GFDL-1.2-invariants-or-later",
        "GFDL-1.2-no-invariants-only",
        "GFDL-1.2-no-invariants-or-later",
        "GFDL-1.2-or-later",
        "GFDL-1.3-invariants-only",
        "GFDL-1.3-invariants-or-later",
        "GFDL-1.3-no-invariants-only",
        "GFDL-1.3-no-invariants-or-later",
        "GFDL-1.3-or-later",
        "GLWTPL",
        "GPL-1.0-or-later",
        "GPL-2.0-or-later",
        "GPL-3.0-or-later",
        "Hippocratic-2.1",
        "HPND-sell-variant",
        "HTMLTIDY",
        "JPNIC",
        "LGPL-2.0-or-later",
        "LGPL-2.1-or-later",
        "LGPL-3.0-or-later",
        "libpng-2.0",
        "libselinux-1.0",
        "Linux-OpenIB",
        "MIT-0",
        "MIT-Modern-Variant",
        "MIT-open-group",
        "MulanPSL-1.0",
        "MulanPSL-2.0",
        "NAIST-2003",
        "NCGL-UK-2.0",
        "Net-SNMP",
        "NIST-PD",
        "NIST-PD-fallback",
        "ODC-By-1.0",
        "OFL-1.0-no-RFN",
        "OFL-1.0-RFN",
        "OFL-1.1-no-RFN",
        "OFL-1.1-RFN",
        "OGC-1.0",
        "OGDL-Taiwan-1.0",
        "OGL-Canada-2.0",
        "OGL-UK-1.0",
        "OGL-UK-2.0",
        "OGL-UK-3.0",
        "O-UDA-1.0",
        "Parity-6.0.0",
        "Parity-7.0.0",
        "PolyForm-Noncommercial-1.0.0",
        "PolyForm-Small-Business-1.0.0",
        "PSF-2.0",
        "Sendmail-8.23",
        "SHL-0.5",
        "SHL-0.51",
        "SSH-OpenSSH",
        "SSH-short",
        "SSPL-1.0",
        "TAPR-OHL-1.0",
        "TCP-wrappers",
        "TU-Berlin-1.0",
        "TU-Berlin-2.0",
        "UCL-1.0",
        "Unicode-DFS-2015",
        "Unicode-DFS-2016",
        "Proprietary",
        "Other",
        "Not licensed",
        "Freeware",
    }
)

# GPL-family identifiers written with a bare major version, e.g.
# "LGPL-3-or-later", which the family fallback in license_normalizer can emit.
_BARE_MAJOR = re.compile(r"^((?:A|L)?GPL)-(\d+)(-or-later)?$")


def to_biotools_license(spdx: str | None) -> str | None:
    """Return an identifier bio.tools accepts, or None when there is no mapping.

    Returning None is deliberate. The caller omits the field, which costs one
    licence; sending a value outside the enumeration costs the whole record.

    >>> to_biotools_license("GPL-3.0-only")
    'GPL-3.0'
    >>> to_biotools_license("GPL-3.0-or-later")
    'GPL-3.0-or-later'
    >>> to_biotools_license("LGPL-3-or-later")
    'LGPL-3.0-or-later'
    >>> to_biotools_license("MIT")
    'MIT'
    >>> to_biotools_license("NOT-A-LICENCE") is None
    True
    >>> to_biotools_license(None) is None
    True
    """
    if not spdx:
        return None
    candidate = spdx.strip()
    if candidate in BIOTOOLS_LICENSES:
        return candidate

    # "-only" postdates the enumeration; the plain identifier means the same.
    if candidate.endswith("-only"):
        stripped = candidate[: -len("-only")]
        if stripped in BIOTOOLS_LICENSES:
            return stripped

    # Pad a bare major version: LGPL-3-or-later -> LGPL-3.0-or-later.
    match = _BARE_MAJOR.match(candidate)
    if match:
        padded = f"{match.group(1)}-{match.group(2)}.0{match.group(3) or ''}"
        if padded in BIOTOOLS_LICENSES:
            return padded
        if padded.endswith("-or-later"):
            plain = padded[: -len("-or-later")]
            if plain in BIOTOOLS_LICENSES:
                return plain

    return None
